// File generated by FlutterFire CLI.
// ignore_for_file: type=lint
import 'package:firebase_core/firebase_core.dart' show FirebaseOptions;
import 'package:flutter/foundation.dart'
    show defaultTargetPlatform, kIsWeb, TargetPlatform;

/// Default [FirebaseOptions] for use with your Firebase apps.
///
/// Example:
/// ```dart
/// import 'firebase_options.dart';
/// // ...
/// await Firebase.initializeApp(
///   options: DefaultFirebaseOptions.currentPlatform,
/// );
/// ```
class DefaultFirebaseOptions {
  static FirebaseOptions get currentPlatform {
    if (kIsWeb) {
      return web;
    }
    switch (defaultTargetPlatform) {
      case TargetPlatform.android:
        return android;
      case TargetPlatform.iOS:
        return ios;
      case TargetPlatform.macOS:
        return macos;
      case TargetPlatform.windows:
        return windows;
      case TargetPlatform.linux:
        throw UnsupportedError(
          'DefaultFirebaseOptions have not been configured for linux - '
          'you can reconfigure this by running the FlutterFire CLI again.',
        );
      default:
        throw UnsupportedError(
          'DefaultFirebaseOptions are not supported for this platform.',
        );
    }
  }

  static const FirebaseOptions web = FirebaseOptions(
    apiKey: 'AIzaSyA7qcmKOlSWTNn3_Pey7QJM1uFiE-PuXdg',
    appId: '1:258099890778:web:264713d943a8c614326663',
    messagingSenderId: '258099890778',
    projectId: 'projeto-integrador-3-b2fdf',
    authDomain: 'projeto-integrador-3-b2fdf.firebaseapp.com',
    storageBucket: 'projeto-integrador-3-b2fdf.firebasestorage.app',
    measurementId: 'G-H3GDZL1HGJ',
  );

  static const FirebaseOptions android = FirebaseOptions(
    apiKey: 'AIzaSyC8gtMoYmdoMisYkaMjVzLwWfRtZy-aQXo',
    appId: '1:258099890778:android:d87770bf0f85af38326663',
    messagingSenderId: '258099890778',
    projectId: 'projeto-integrador-3-b2fdf',
    storageBucket: 'projeto-integrador-3-b2fdf.firebasestorage.app',
  );

  static const FirebaseOptions ios = FirebaseOptions(
    apiKey: 'AIzaSyCNZgVrs7fHWZ0Rt-GAjS7O6mFSXvcrLhI',
    appId: '1:258099890778:ios:a57ebcd0a0f3ea28326663',
    messagingSenderId: '258099890778',
    projectId: 'projeto-integrador-3-b2fdf',
    storageBucket: 'projeto-integrador-3-b2fdf.firebasestorage.app',
    iosBundleId: 'com.example.projetoIntegrador3',
  );

  static const FirebaseOptions macos = FirebaseOptions(
    apiKey: 'AIzaSyCNZgVrs7fHWZ0Rt-GAjS7O6mFSXvcrLhI',
    appId: '1:258099890778:ios:a57ebcd0a0f3ea28326663',
    messagingSenderId: '258099890778',
    projectId: 'projeto-integrador-3-b2fdf',
    storageBucket: 'projeto-integrador-3-b2fdf.firebasestorage.app',
    iosBundleId: 'com.example.projetoIntegrador3',
  );

  static const FirebaseOptions windows = FirebaseOptions(
    apiKey: 'AIzaSyA7qcmKOlSWTNn3_Pey7QJM1uFiE-PuXdg',
    appId: '1:258099890778:web:2d8bae362bc7b11b326663',
    messagingSenderId: '258099890778',
    projectId: 'projeto-integrador-3-b2fdf',
    authDomain: 'projeto-integrador-3-b2fdf.firebaseapp.com',
    storageBucket: 'projeto-integrador-3-b2fdf.firebasestorage.app',
    measurementId: 'G-8PEG8E9DQY',
  );
}
